-- Číslo cesty z topa (zhoduje sa s číslom nakresleným na fotke). Varianty a kombinácie číslo nemajú.
ALTER TABLE public.climbs
    ADD COLUMN IF NOT EXISTS topo_number smallint;

UPDATE public.climbs c
SET topo_number = v.topo_number
FROM (VALUES
    ('Sedembolestný', 'Ježiškov spacáčik', 1),
    ('Sedembolestný', 'Stigmy', 2),
    ('Sedembolestný', 'Najsvetlejšia tma', 3),
    ('Moonboard', 'Listomor', 1),
    ('Moonboard', 'Puklinár', 2),
    ('Moonboard', 'Čiara', 3),
    ('Moonboard', 'Liana', 4),
    ('Moonboard', 'One size fits all', 5),
    ('Moonboard', 'Obdobie sucha', 6),
    ('Moonboard', 'Klimatická kríza', 7),
    ('Prízemie', 'Majka', 1),
    ('Prízemie', 'Kvašňák', 2),
    ('Prízemie', 'Valko', 3),
    ('Prízemie', 'Kompiš', 4),
    ('Prízemie', 'Gurun', 5),
    ('Prízemie', 'Majka z Gurunu', 6),
    ('Prízemie', 'Čabovce', 7),
    ('Prízemie', 'Václav Borovička', 8),
    ('Prízemie', 'Nadpozemská noha', 9),
    ('Prízemie', 'Kto kráča po vode', 10),
    ('Prízemie', 'Bloody Mary', 11),
    ('Prízemie', 'Ľavica', 1),
    ('Prízemie', 'Pravica', 2),
    ('Prízemie', 'Kadisvet', 3),
    ('Prízemie', 'Lokál Borec', 1),
    ('Prízemie', 'Mravčí variant', 2),
    ('Prízemie', 'Mravčie vojny', 3),
    ('Prízemie', 'Blízke diaľavy', 4),
    ('Prízemie', 'Kamarát Ostriež', 5),
    ('Prízemie', 'Slimačím tempom', 6),
    ('Prízemie', 'Fleet Street', 7),
    ('Prízemie', 'Nadrobno', 8),
    ('Prízemie', 'Tŕne pichľavého svedomia', 9),
    ('Prízemie', 'Prierez kamennej tvorby', 10),
    ('Prízemie', 'Elektrik', 11),
    ('Prízemie', 'Banálna story', 12),
    ('Prízemie', 'Storyline', 13),
    ('Prízemie', 'Linestory', 14),
    ('Prízemie', 'Sweeniar Todd', 15),
    ('Prízemie', 'Mantelko', 16),
    ('Prízemie', 'Tupé tŕne', 17),
    ('Prízemie', 'Zážitky zo šachty', 1),
    ('Prízemie', 'Paternoster', 2),
    ('Prízemie', 'Výťah opäť nechodí', 3),
    ('Prízemie', 'Pre veteránov', 4),
    ('Prízemie', 'Strom je láva', 5),
    ('Prízemie', 'Elevátorko', 6),
    ('Prízemie', 'Akrofóbia', 7),
    ('Prízemie', 'Prevádzková štúdia', 8),
    ('Prízemie', 'Infantilko', 1),
    ('Pod Medeným', 'Nechaj sa viesť', 1),
    ('Pod Medeným', 'From Dirt Grows the Trees', 2),
    ('Pod Medeným', 'Return of the Sleep Waker', 3),
    ('Pod Medeným', 'Čó ja?', 4),
    ('Pod Medeným', 'Honey báger', 5),
    ('Pod Medeným', 'Nech sa ľúbi', 6),
    ('Pod Medeným', 'Špinavá krása', 7),
    ('Pod Medeným', 'Nechaj sa ľúbiť', 8),
    ('Pod Medeným', 'Zľava', 9),
    ('Pod Medeným', 'Zľava na prekvapenia', 10),
    ('Pod Medeným', 'Nečakaný návrat', 11),
    ('Pod Medeným', 'Amerika v noci', 1),
    ('Poschodie', 'Devina', 1),
    ('Poschodie', 'Štvorka', 2),
    ('Poschodie', 'Zlatá horúčka', 3),
    ('Poschodie', 'Biela zlatá horúčka', 4),
    ('Poschodie', 'Zahájenie', 5),
    ('Poschodie', 'Sivá mágia', 6),
    ('Poschodie', 'Sivobiela mágia', 7),
    ('Poschodie', 'Biela mágia', 8),
    ('Poschodie', 'Hlavolam', 9),
    ('Poschodie', 'Suchár', 10),
    ('Poschodie', 'Suchá voda', 11),
    ('Poschodie', 'Plytká bolesť', 12),
    ('Poschodie', 'Plytká radosť', 13),
    ('Poschodie', 'Modrá karikatúra', 14),
    ('Poschodie', 'Potápač', 15),
    ('Poschodie', 'Pravý potápač', 16),
    ('Poschodie', 'Hlboká bolesť', 17),
    ('Poschodie', 'Voda na suchu', 18),
    ('Poschodie', 'Kornútok', 1),
    ('Poschodie', 'Paplónik', 1),
    ('Poschodie', 'Vankúšik', 2),
    ('Poschodie', 'Perinka', 3),
    ('Poschodie', 'Gilotína', 1),
    ('Poschodie', 'Láskobrána', 2),
    ('Poschodie', 'Láskobrána SD', 3),
    ('Poschodie', 'Madame Déficit', 4),
    ('Poschodie', 'Mária Antoinetta', 5),
    ('Poschodie', 'Stará novina', 1),
    ('Poschodie', 'Nová doba', 2),
    ('Poschodie', 'Old School', 3),
    ('Poschodie', 'Suťovec', 1),
    ('Poschodie', 'Nesúť ho', 2),
    ('Poschodie', 'Ranger', 1),
    ('Poschodie', 'Raptor', 2),
    ('Poschodie', 'Velociraptor', 3),
    ('Poschodie', 'Dojímavo', 1),
    ('Poschodie', 'Doják', 2),
    ('Poschodie', 'Lombardér', 1),
    ('Poschodie', 'Lombarber', 2),
    ('Poschodie', 'Barber', 3),
    ('Poschodie', 'Sivá eminencia', 4),
    ('Poschodie', 'Črep', 5),
    ('Poschodie', 'Chujko Putin', 6),
    ('Poschodie', 'Superslab', 7),
    ('Poschodie', 'Črepiny', 8),
    ('Poschodie', 'Trestuhodná obliezka', 1),
    ('Poschodie', 'Preliezkavo', 2),
    ('Poschodie', 'Rozliezkavo', 3),
    ('Poschodie', 'Reverzík', 4),
    ('Poschodie', 'Direktík', 5),
    ('Vlna', 'Spenené mliečko', 1),
    ('Vlna', 'Doparoma', 2),
    ('Vlna', 'Ľahké ruky', 3),
    ('Vlna', 'Ťažké nohy', 4),
    ('Vlna', 'Naháňačka zážitkov', 5),
    ('Vlna', 'Vlna', 6),
    ('Vlna', 'Kmit', 7),
    ('Vlna', 'Geometria pohybu', 8),
    ('Vlna', 'Geometria ohybu', 9),
    ('Vlna', 'Ostrá snaha', 10),
    ('Vlna', 'Takmer skvelé', 11),
    ('Vlna', 'Nevynechaj radosť', 12),
    ('Vlna', 'Moai', 13),
    ('Vlna', 'Tu sme skončili', 14)
) AS v(sector, name, topo_number),
     public.boulders b,
     public.sectors s,
     public.areas a
WHERE c.boulder_id = b.id
  AND b.sector_id = s.id
  AND s.area_id = a.id
  AND a.name = 'Medené Hámre'
  AND s.name = v.sector
  AND c.name = v.name;

-- Kombinácie na Hlave sú nakreslené na tej istej fotke ako Hlava 6
UPDATE public.boulders b
SET image_url = h.image_url
FROM public.boulders h
WHERE b.name = 'Hlava – kombinácie'
  AND h.name = 'Hlava 6'
  AND h.sector_id = b.sector_id;
